In [2]:
import numpy as np
from scipy.linalg import schur,eigvals

arr = np.array([[0,2,2],[0,1,2],[1,0,1]])

T , Z = schur(arr)

print(T)
print(Z)

[[ 2.65896708  1.42440458 -1.92933439]
 [ 0.         -0.32948354 -0.49063704]
 [ 0.          1.31178921 -0.32948354]]
[[ 0.72711591 -0.60156188  0.33079564]
 [ 0.52839428  0.79801892  0.28976765]
 [ 0.43829436  0.03590414 -0.89811411]]
